---
title: "Untitled"
output: 
  bookdown::word_document2:
   keep_tex: true
header-includes:
  - \usepackage[caption=false]{subfig}
  - \usepackage{float}
date: '2022-06-11'
---

```{r setup, include=FALSE}
library(EviewsR)
knitr::opts_chunk$set(echo = T,prompt = T,fig.align = "center",fig.pos="h",eval = T)
options(par)
# set_eviews_path("eviews10")
```



# R plots




```{eviews saniya,fig.cap= 'Figures automatically imported by eviews'}
#| fig.cap: Figures importd 
#| fig.subcap: !expr paste(rep("Figure",9),1:3,"of",rep(c("EviewsR","Page1","Page2"),each=3),"page")
#| fig.show: asis
#| graph_procs: [template magazine,legend position(right)]
#| out.width: #0.3\textwidth
#| fig.pos: H
#| out.height: #0.25\textwidth
#| fig.ncol: 3
#| echo: FALSE
#| page: small
#| eval: true

'This is some comment in EViews program, feel free to write anything

wfcreate(page=EviewsR_page,wf=EviewsR_workfile) m 2000 2022
for %y small small2  small3 
pagecreate(page={%y}) EviewsR q 2000 2022
pageselect {%y}
rndseed 123
genr x=@cumsum(nrnd)
genr y=@cumsum(nrnd)
genr z=@cumsum(nrnd)
equation OLS_EQUATION.ls y c x z
freeze(OLS_EQUATION_TABLE,mode=overwrite) OLS_EQUATION
delete(noerr) GRAPH*
freeze(sag3,mode=overwrite) z.line
graph sag2.dot y
graph sag1.area x
sag3.addtext(ar) %y
sag2.addtext(ar) %y
sag1.addtext(ar) %y
next
```


```{r}
#| fig.cap: some plot again
#| fig.subcap: !expr 1:9
#| out.width: #0.3\textwidth
#| fig.ncol: 3
#| fig.show: hold

library(magrittr)

a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
```



```{r}
#| fig.cap: some plot
#| fig.subcap: !expr 1:9
#| out.width: #0.3\textwidth
#| fig.ncol: 3
#| fig.show: hold

library(magrittr)

a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
a=runif(100) %>% plot
```



```{eviews biscuit,fig.cap= 'Figures automatically imported by eviews 2'}
#| fig.subcap: !expr paste(rep("Figure",9),1:3,"of",rep(c("EviewsR","Page1","Page2"),each=3),"page")
#| graph_procs: [template magazine,legend position(right)]
#| out.width: #0.3\textwidth
#| #out.height: 0.25\textwidth
#| fig.ncol: 3
#| fig.show: asis
#| echo: FALSE
#| page: page1 page2

'This is some comment in EViews program, feel free to write anything

wfcreate(page=EviewsR_page,wf=EviewsR_workfile) m 2000 2022
for %y page1 EviewsR  page2 
pagecreate(page={%y}) EviewsR q 2000 2022
pageselect {%y}
rndseed 123
genr x=@cumsum(nrnd)
genr y=@cumsum(nrnd)
genr z=@cumsum(nrnd)
equation OLS_EQUATION.ls y c x z
freeze(OLS_EQUATION_TABLE,mode=overwrite) OLS_EQUATION
delete(noerr) GRAPH*
freeze(GRAPH3,mode=overwrite) z.line
graph GRAPH2.dot y
graph GRAPH1.area x
graph3.addtext(ar) %y
graph2.addtext(ar) %y
graph1.addtext(ar) %y
next
```



```{ditaa,eval=F}
/----\ /----\
|c33F| |cC02|
|    | |    |
\----/ \----/

/----\ /----\
|c1FF| |c1AB|
|    | |    |
\----/ \----/

```
