---
title: "Untitled"
output: 
  bookdown::pdf_document2:
   keep_tex: true
header-includes:
  - \usepackage[caption=false]{subfig}
  - \usepackage{float}
date: '2022-06-11'
---

```{r setup, include=FALSE}
library(EviewsR)
knitr::opts_chunk$set(echo = T,prompt = T,fig.align = "center",fig.pos="h",eval = T)

# set_eviews_path("eviews10")
```


```{eviews EviewsR3}
#| fig.cap: Figures automatically imported by eviews chunk (page="eviewsr page1", fig.keep="new")
#| fig.subcap: !expr paste0(rep("Graph",6),3:1," of ",rep(c("EviewsR","Page1"),each=3)," page")
#| graph_procs: [template bokeh, setelem(1) lcolor(green) fillcolor(green)]
#| out.width: 0.33\textwidth
#| out.height: 0.25\textwidth
#| fig.ncol: 3
#| fig.keep: new
#| page: eviewsr3 page1
#| echo: FALSE
#| eval: false

'This is some comment in EViews program, feel free to write anything

wfcreate(page=EviewsR_page,wf=EviewsR_workfile) m 2000 2022
for %y  page2 EviewsR3 page1 
pagecreate(page={%y}) EviewsR q 2000 2022
pageselect {%y}
rndseed 123
genr x=@cumsum(nrnd)
genr y=@cumsum(nrnd)
genr z=@cumsum(nrnd)
equation OLS_EQUATION.ls y c x z
freeze(OLS_EQUATION_TABLE,mode=overwrite) OLS_EQUATION
delete(noerr) GRAPH*
freeze(GRAPH3,mode=overwrite) z.line
graph GRAPH2.dot y
graph GRAPH1.area x
graph3.addtext(ar) %y
graph2.addtext(ar) %y
graph1.addtext(ar) %y
next
```



```{r,echo=FALSE,eval=FALSE}
x=runif(100)
y=runif(100)
EviewsRDataFrame=data.frame(x,y)
dir.create('EviewsR_files/')
write.csv(EviewsRDataFrame,"EviewsR_Files/EviewsR_eviews_import.csv",row.names = FALSE)
```


```{r eviewsImport,eval=FALSE}
eviews_import(source_description = "EviewsR_Files/EviewsR_eviews_import.csv",frequency = "m",start_date = "1990",save_path ='EviewsR_Files' )
```


```{r eviewsImport1,eval=FALSE}

eviews_import(source_description = "EviewsR_files/EviewsR_eviews_import.csv",smpl_string = "1990m10 1992m11",
rename_string = "x x2")

```


```{asy abc, fig.cap='some nice flowchart',settings.prc = F}
settings.prc = false
size(0,300);

import flowchart;

block block1=rectangle(Label("Example",magenta),
                       pack(Label("Start:",heavygreen),"",Label("$A:=0$",blue),
                            "$B:=1$"),(-0.5,3),palegreen,paleblue,red);
block block2=diamond(Label("Choice?",blue),(0,2),palegreen,red);
block block3=roundrectangle("Do something",(-1,1));
block block4=bevel("Don't do something",(1,1));
block block5=circle("End",(0,0));

draw(block1);
draw(block2);
draw(block3);
draw(block4);
draw(block5);

add(new void(picture pic, transform t) {
    blockconnector operator --=blockconnector(pic,t);
    //    draw(pic,block1.right(t)--block2.top(t));
    block1--Right--Down--Arrow--block2;
    block2--Label("Yes",0.5,NW)--Left--Down--Arrow--block3;
    block2--Right--Label("No",0.5,NE)--Down--Arrow--block4;
    block4--Down--Left--Arrow--block5;
    block3--Down--Right--Arrow--block5;
  });

```
