---
title: "Untitled"
output: 
  bookdown::pdf_document2:
   keep_tex: true
header-includes:
  - \usepackage{subfig}
date: '2022-06-11'
---

```{r setup, include=FALSE}
options(prompt = "EViews> ")
library(EviewsR)
knitr::opts_chunk$set(echo = F,prompt = T,fig.align = "center",fig.pos="h",out.width = "0.45\\textwidth",eval = T)

# set_eviews_path("eviews10")
```

## R Markdown

```{eviews mychunk,page="mati page2 page1 page3" ,prompt=T,eval=T,fig.cap="somefigure",fig.subcap=paste("Page",rep(1:4,each=4),"Figure",1:4)}
#| fig.show: hold
#| graph_procs: 
#| - legend columns(auto) position(right)
#| - template midnight
#| page: page1 page2
#| fig.keep: new
#| out.width: 0.25\textwidth
#| fig.align: center

wfcreate(wf=sagiru,page=mati) q 2000 2025
'open mychunk

for !i=1 to 100
%page="page"+@STR(!i)
if @pageexist(%page) then
pagedelete page!i
endif
next

for %y page1 page2 page3  

pagecreate(page={%y}) a 2020 2025
next
%pagelist="page1 page2 page3"
for %y {%pagelist}
pageselect {%y}
delete(noerr) grap
genr y=@cumsum(nrnd)
genr x=@cumsum(nrnd)
genr z=@cumsum(nrnd)
genr date=@date
  graph grap3.line z   
              graph grap2.bar y 
                          graph grap1.area x  
   freeze(grap,mode=overwrite) x.line
equation ols.ls y c x
freeze(mode=overwrite,tab) ols
next
'wfsave mychunk

```



```{r,eval=F}
library(magrittr)

mychunk$page3 %>% head

mychunk$ols 

mychunk$tab

mychunk$mati %>% head 
```

# R plots



```{r labe,fig.cap="another fig",eval=F}
print(knitr::opts_current$get("sagir"))
print(knitr::opts_current$get("fig.show"))
y=cumsum(rnorm(100))
x=cumsum(rnorm(100))

plot(x,y)
```

```{r eview-graph,eval=F}
data=data.frame(y=runif(100),x=runif(100))
eviews_graph(data,save_path = "",frequency = "m",start_date = 1990,group = F,options = "m",graph_procs = "template eviews5")

```


```{r rwalk,eval=F}
rwalk("x y z",num_observations = 100,frequency = "7",start_date = "1")

eviews$xyz %>% head

eviews_graph(eviews$xyz,group = T,graph_procs = "template midnight",graph_command = "line")
```



```{eviews sagirumati,eval=T,page=T,fig.show="hold",fig.cap="Dynamic figure",fig.keep='new',graph_procs="template midnight"}
'This is some comment in EViews program, feel free to write anything

wfcreate(page=EviewsR_page,wf=EviewsR_workfile) m 2000 2022
for %y sam package page1 page2
pagecreate(page={%y}) sam m 2000 2022
next
pageselect sam
rndseed 123456
genr y=@cumsum(nrnd)
genr x=@cumsum(nrnd)
equation OLS_EQUATION.ls y c x
freeze(OLS_EQUATION_TABLE,mode=overwrite) OLS_EQUATION
freeze(EviewsR_GRAPH,mode=overwrite) y.line
delete(noerr) EviewsR_GRAPH1
graph GRAPH1.line x y
save mygraph
```


```{r grap,fig.cap="A nice figure",fig.show="hold"}
import_graph("*","mygraph","sam",graph_procs = "template magazine")

```



```{eviews EviewsR1}
#| page: TRUE
#| fig.cap: Dynamic figure automatically imported by eviews chunk
#| fig.subcap: [Sub-figure 1, Sub-figure 2]
#| graph_procs: [template bokeh,legend position(right)]
#| out.width: 0.48\textwidth
#| out.height: 0.4\textwidth

'This is some comment in EViews program, feel free to write anything

wfcreate(page=EviewsR_page,wf=EviewsR_workfile) m 2000 2022
for %y EviewsR package page1 page2
pagecreate(page={%y}) EviewsR m 2000 2022
next
pageselect EviewsR
rndseed 123456
genr y=@cumsum(nrnd)
genr x=@cumsum(nrnd)
equation OLS_EQUATION.ls y c x
freeze(OLS_EQUATION_TABLE,mode=overwrite) OLS_EQUATION
freeze(EviewsR_GRAPH,mode=overwrite) y.line
delete(noerr) EviewsR_GRAPH1
graph EviewsR_GRAPH1.line x y
```
