'OPTIONS
{%graph}.options frameaxes(bl) framewidth(0.375) gridwidth(0.375) gridcolor(100,100,255)
{%graph}.axis(l) format(prefix="N")
{%graph}.textdefault font(Times New Roman,20,-b,-i,-u,-s)
graphs_of_y_x.setfont legend(Arial,20,b,-i,-u,-s) text(Arial,20,-b,-i,-u,-s) obs(Arial,20,b,-i,-u,-s) axis(Arial,20,b,-i,-u,-s)
{%graph}.setelem(1) symbol(CIRCLE)
{%graph}.setelem(1) symbol(CIRCLE)
{%graph}.setelem(1) linewidth(3)
{%graph}.setelem(1) symbolsize(Large) linepattern(none)
{%graph}.setelem(1) linepattern(SOLID)
graphs_of_y_x.setelem(1) symbolsize(Large) linewidth(10) linepattern(none) symbol(square)
{%graph}.legend position(RIGHT)
